### ISSUE TITLE
Exercise solutions?

### ISSUE THREAD

**Issue by AdnanHodzic** [PacktPublishing/Mastering-Go-Second-Edition#1]
Hi, 

I'm really enjoying this book, but I really can't figure out solutions to some of the exercises. Would it be possible to also include code samples for these as well?

This way we could get some help in case we get stuck, or even compare our solutions to your solutions. 

Thanks!

**Comment by mactsouk** [comment]
Hello.

I can give you some hints if you want. Please ask.

**Comment by AdnanHodzic** [comment]
Hey! 

I'm working on "find the sum of all command-line arguments that are valid numbers" exercise. I have a solution which I'm not happy with it. 

Namely, I limited program to only accept 2 arguments, it will report if provided arguments are not numbers and if they are it will return their sum. But I would like to be able to provide as many arguments as I want, what am I doing wrong? (obviously last part of code is the problem)

Source:

```
// finds the sum of all command-line arguments that are valid numbers.
package main

import (
	"errors"
	"fmt"
	"os"
	"strconv"
)

func main() {
	argsWithoutApp := os.Args[1:]
	if len(os.Args) < 3 {
		fmt.Println("Please provide 2 numbers.")
		os.Exit(1)
	} else if len(os.Args) >= 4 {
		fmt.Println("You've entered more then 2 numbers.")
		os.Exit(1)
	}

	arguments := os.Args
	var err error = errors.New("An error")
	k := 1
	var n float64
	for err != nil {
		if k >= len(arguments) {
			fmt.Println("None of the arguments is a number!")
			return
		}
		n, err = strconv.ParseFloat(arguments[k], 64)
		k++
	}

	num1, num2 := n, n
	for i := 2; i < len(arguments); i++ {
		n, err := strconv.ParseFloat(arguments[i], 64)
		if err == nil {
			if n < num1 {
				num1 = n
			}
			if n > num2 {
				num2 = n
			}
		}
	}

	fmt.Println("Total sum of provided", argsWithoutApp, "numbers is:", num1+num2)
}
```

Output: 
```
go run ExerciseArgsValidNum.go 4 3

Total sum of provided [4 3] numbers is: 7
```

**Comment by mactsouk** [comment]
First, you will have to think how you are going to solve the problem. Then, you will have to implement it and make sure that the code does what you want.
The last `for` loop in your code is not related to the solution.

**Comment by mactsouk** [comment]
You might find the following code useful:

```package main

import (
	"fmt"
	"os"
	"strconv"
)

func main() {
	arguments := os.Args
	sum := 0
	for i := 1; i < len(arguments); i++ {
		temp, _ := strconv.Atoi(arguments[i])
		sum = sum + temp
	}
	fmt.Println("Sum:", sum)
}
```

**Comment by AdnanHodzic** [comment]
This exactly what I needed. In one of my versions I wrote identical for loop, but crucial part I was missing was: `temp, _ := strconv.Atoi(arguments[i])`

Thank you for your assistance, much appreciated!
